### ISSUE TITLE
Change delay field to numeric

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/geocoder#20]
Suggestion: change the "Delay between Google geocoding requests (in milliseconds)" to a numeric field, and set the default to be the recommended value. One issue I ran into was that I had added the `ms` behind the number.

![Screen Shot 2020-08-31 at 3 45 26 PM](https://user-images.githubusercontent.com/871421/91770227-70ee8600-eba6-11ea-8c77-5cc39fdcd9c2.jpg)

**Comment by jenlampton** [comment]
I just pushed a commit that switches this field from text to number, and adds the `ms` units as a field suffix so that it is not accidentally included. 
<img width="676" alt="Screen Shot 2023-02-13 at 2 55 13 PM" src="https://user-images.githubusercontent.com/397895/218592966-a7c36360-d6bd-494f-9f07-3f57ae3393cc.png">
